//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizSystem.Domain.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuizSystem.Domain.Exceptions.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin NationalCode is invalid.
        /// </summary>
        public static string AdminNationalCodeInvalidExceptionMessage {
            get {
                return ResourceManager.GetString("AdminNationalCodeInvalidExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer title already exists in the question.
        /// </summary>
        public static string AnswerTitleAlreadyExistsExceptionMessage {
            get {
                return ResourceManager.GetString("AnswerTitleAlreadyExistsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student already exists and can not be added to the course.
        /// </summary>
        public static string CourseAddStudentAlreadyExistsExceptionMessage {
            get {
                return ResourceManager.GetString("CourseAddStudentAlreadyExistsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date is earlier than start date.
        /// </summary>
        public static string CourseEndTimeIsBeforeStartTimeExceptionMessage {
            get {
                return ResourceManager.GetString("CourseEndTimeIsBeforeStartTimeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course does not exist.
        /// </summary>
        public static string CourseIdNotExistExceptionMessage {
            get {
                return ResourceManager.GetString("CourseIdNotExistExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor is null for course.
        /// </summary>
        public static string CourseProfessorNotExistExceptionMessage {
            get {
                return ResourceManager.GetString("CourseProfessorNotExistExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time period is too short for a course.
        /// </summary>
        public static string CourseShortPeriodExceptionMessage {
            get {
                return ResourceManager.GetString("CourseShortPeriodExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time for course is in the past.
        /// </summary>
        public static string CourseStartTimeInThePastExceptionMessage {
            get {
                return ResourceManager.GetString("CourseStartTimeInThePastExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student is null for adding to course.
        /// </summary>
        public static string CourseStudentAddNullExceptionMessage {
            get {
                return ResourceManager.GetString("CourseStudentAddNullExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title already exists.
        /// </summary>
        public static string CourseTitleExistsExceptionMessage {
            get {
                return ResourceManager.GetString("CourseTitleExistsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam doesn&apos;t exist.
        /// </summary>
        public static string ExamNotExistExceptionMessage {
            get {
                return ResourceManager.GetString("ExamNotExistExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExamStudent Exam not exist.
        /// </summary>
        public static string ExamStudentExamIdNotExistExceptionMessage {
            get {
                return ResourceManager.GetString("ExamStudentExamIdNotExistExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExamStudent doestn&apos;t exist.
        /// </summary>
        public static string ExamStudentNotExistExceptionMessage {
            get {
                return ResourceManager.GetString("ExamStudentNotExistExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam time is too short.
        /// </summary>
        public static string ExamTimeShortExceptionMessage {
            get {
                return ResourceManager.GetString("ExamTimeShortExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam title already exists.
        /// </summary>
        public static string ExamTitleExistException {
            get {
                return ResourceManager.GetString("ExamTitleExistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question already exists in this exam.
        /// </summary>
        public static string GradedQuestionDuplicateExceptionMessage {
            get {
                return ResourceManager.GetString("GradedQuestionDuplicateExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GradedQuestion doesn&apos;t exist.
        /// </summary>
        public static string GradedQuestionNotExistExceptionMessage {
            get {
                return ResourceManager.GetString("GradedQuestionNotExistExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade should have a value.
        /// </summary>
        public static string GradeQuestionGradeExceptionMessage {
            get {
                return ResourceManager.GetString("GradeQuestionGradeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question already has a right answer.
        /// </summary>
        public static string MultipleChoiceAnswerAlreadyHasRightAnswerExceptionMessage {
            get {
                return ResourceManager.GetString("MultipleChoiceAnswerAlreadyHasRightAnswerExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course does not exist to add to Professor.
        /// </summary>
        public static string ProfessorAddCourseNotExistExceptionMessage {
            get {
                return ResourceManager.GetString("ProfessorAddCourseNotExistExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The birthdate is too old or too young.
        /// </summary>
        public static string ProfessorBirthDateInvalidValueExceptionMessage {
            get {
                return ResourceManager.GetString("ProfessorBirthDateInvalidValueExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName is Required for Professor.
        /// </summary>
        public static string ProfessorFirstNameRequiredExceptionMessage {
            get {
                return ResourceManager.GetString("ProfessorFirstNameRequiredExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor Id doesn&apos;t exist .
        /// </summary>
        public static string ProfessorIdNotExistExceptionMessage {
            get {
                return ResourceManager.GetString("ProfessorIdNotExistExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName is Required for Professor.
        /// </summary>
        public static string ProfessorLastNameRequiredExceptionMessage {
            get {
                return ResourceManager.GetString("ProfessorLastNameRequiredExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor National Code already exists.
        /// </summary>
        public static string ProfessorNationalCodeExistsExceptionMessage {
            get {
                return ResourceManager.GetString("ProfessorNationalCodeExistsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor NationalCode is invalid.
        /// </summary>
        public static string ProfessorNationalCodeInvalidExceptionMessage {
            get {
                return ResourceManager.GetString("ProfessorNationalCodeInvalidExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question doesn&apos;t exist.
        /// </summary>
        public static string QuestionNotExistExceptionMessage {
            get {
                return ResourceManager.GetString("QuestionNotExistExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question title already exists.
        /// </summary>
        public static string QuestionTitleExistsExceptionMessage {
            get {
                return ResourceManager.GetString("QuestionTitleExistsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must be shorter than 20 characters.
        /// </summary>
        public static string QuestionTitleLengthLongExceptionMessage {
            get {
                return ResourceManager.GetString("QuestionTitleLengthLongExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Id doesn&apos;t exist .
        /// </summary>
        public static string StudentIdNotExistExceptionMessage {
            get {
                return ResourceManager.GetString("StudentIdNotExistExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Code already exists.
        /// </summary>
        public static string StudentNationalCodeExistsExceptionMessage {
            get {
                return ResourceManager.GetString("StudentNationalCodeExistsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student NationalCode is invalid.
        /// </summary>
        public static string StudentNationalCodeInvalidException {
            get {
                return ResourceManager.GetString("StudentNationalCodeInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The birthdate is too old or too young.
        /// </summary>
        public static string UserBirthDateInvalidValueExceptionMessage {
            get {
                return ResourceManager.GetString("UserBirthDateInvalidValueExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName is Required for User.
        /// </summary>
        public static string UserFirstNameRequiredExceptionMessage {
            get {
                return ResourceManager.GetString("UserFirstNameRequiredExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName is Required for User.
        /// </summary>
        public static string UserLastNameRequiredExceptionMessage {
            get {
                return ResourceManager.GetString("UserLastNameRequiredExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password for User isn&apos;t sufficient.
        /// </summary>
        public static string UserPasswordInvalidExceptionMessage {
            get {
                return ResourceManager.GetString("UserPasswordInvalidExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User search type is invalid.
        /// </summary>
        public static string UserSearchTypeInvalidExceptionMessage {
            get {
                return ResourceManager.GetString("UserSearchTypeInvalidExceptionMessage", resourceCulture);
            }
        }
    }
}
