//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizSystem.Domain.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuizSystem.Domain.Exceptions.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time for the course is before start time.
        /// </summary>
        public static string CourseEndTimeIsBeforeStartTimeExceptionMessage {
            get {
                return ResourceManager.GetString("CourseEndTimeIsBeforeStartTimeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time period is too short for a course.
        /// </summary>
        public static string CourseShortPeriodExceptionMessage {
            get {
                return ResourceManager.GetString("CourseShortPeriodExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time for course is in the past.
        /// </summary>
        public static string CourseStartTimeInThePastExceptionMessage {
            get {
                return ResourceManager.GetString("CourseStartTimeInThePastExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title already exists.
        /// </summary>
        public static string CourseTitleExistsExceptionMessage {
            get {
                return ResourceManager.GetString("CourseTitleExistsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The birthdate is too old or too young.
        /// </summary>
        public static string ProfessorBirthDateInvalidValueExceptionMessage {
            get {
                return ResourceManager.GetString("ProfessorBirthDateInvalidValueExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName is Required for Professor.
        /// </summary>
        public static string ProfessorFirstNameRequiredExceptionMessage {
            get {
                return ResourceManager.GetString("ProfessorFirstNameRequiredExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName is Required for Professor.
        /// </summary>
        public static string ProfessorLastNameRequiredExceptionMessage {
            get {
                return ResourceManager.GetString("ProfessorLastNameRequiredExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Code already exists.
        /// </summary>
        public static string ProfessorNationalCodeExistsExceptionMessage {
            get {
                return ResourceManager.GetString("ProfessorNationalCodeExistsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match for this national code and password.
        /// </summary>
        public static string ProfessorNoMatchForNationalCodeAndPasswordExceptionMessage {
            get {
                return ResourceManager.GetString("ProfessorNoMatchForNationalCodeAndPasswordExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The birthdate is too old or too young.
        /// </summary>
        public static string StudentBirthDateInvalidValueExceptionMessage {
            get {
                return ResourceManager.GetString("StudentBirthDateInvalidValueExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName is Required for Student.
        /// </summary>
        public static string StudentFirstNameRequiredExceptionMessage {
            get {
                return ResourceManager.GetString("StudentFirstNameRequiredExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName is Required for Student.
        /// </summary>
        public static string StudentLastNameRequiredExceptionMessage {
            get {
                return ResourceManager.GetString("StudentLastNameRequiredExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Code already exists.
        /// </summary>
        public static string StudentNationalCodeExistsExceptionMessage {
            get {
                return ResourceManager.GetString("StudentNationalCodeExistsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match for this national code and password.
        /// </summary>
        public static string StudentNoMatchForNationalCodeAndPasswordExceptionMessage {
            get {
                return ResourceManager.GetString("StudentNoMatchForNationalCodeAndPasswordExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password for student isn&apos;t sufficient.
        /// </summary>
        public static string StudentPasswordInvalidExceptionMessage {
            get {
                return ResourceManager.GetString("StudentPasswordInvalidExceptionMessage", resourceCulture);
            }
        }
    }
}
